<?php
/**
 * @category    Overdose
 * @package     Overdose_Testimonials
 * @author      Dmytro Kamyshov
 */
?>
<div class="form-add">
    <h2><?php echo $this->__('Write Your Own Testimonial') ?></h2>
    <form action="<?php echo $this->getAction() ?>" method="post" id="testimonial-form">
        <?php echo $this->getBlockHtml('formkey'); ?>
        <div class="fieldset">
            <ul class="form-list">
                <li class="inline-label">
                    <label for="title_field" class="required">
                        <em>*</em>
                        <?php echo $this->__('Title') ?>
                    </label>
                    <div class="input-box">
                        <input type="text" name="title" id="title_field" class="input-text required-entry" value=""/>
                    </div>
                </li>

                <li>
                    <label for="message_field" class="required">
                        <em>*</em>
                        <?php echo $this->__('Message') ?>
                    </label>
                    <div class="input-box">
                        <textarea name="message" id="message_field" cols="5" rows="3" class="required-entry"></textarea>
                    </div>
                </li>

                <li class="inline-label">
                    <label for="image_field" class="required">
                        <em>*</em>
                        <?php echo $this->__("Image") ?>
                    </label>
                    <div class="input-box">
                        <input type="file" name="image" id="image_field" class="input-file required-entry" value=""/>
                    </div>
                </li>
            </ul>
        </div>
        <div class="buttons-set">
            <button type="submit" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Submit Review')) ?>"
                    class="button"><span><span><?php echo $this->__('Submit Review') ?></span></span></button>
        </div>
    </form>
    <script type="text/javascript">
        //<![CDATA[
        var dataForm = new VarienForm('testimonial-form');
        //]]>
    </script>
</div>
